anarion80/ansible-nas

README.md
nas.yml
roles/immich/defaults/main.yml
roles/immich/docs/immich.md
roles/immich/molecule/default/molecule.yml
roles/immich/molecule/default/side_effect.yml
roles/immich/molecule/default/verify.yml
roles/immich/molecule/default/verify_stopped.yml
roles/immich/tasks/main.yml
website/docs/applications/other/immich.md

Add immich

---

roles/firefly/tasks/main.yml
roles/nomad/tasks/main.yml

Pull upstream fixes

---

.github/workflows/docs-test.yml

This is an attempt to fix the "Test Website Deployment" action that always fails currently. I'm not sure why it was using `yarn` when the Deploy action uses `npm`, so I switched it to `npm` for consistency. But is also works with `yarn` after adding `cache-dependency-path` and default working directory.
Fixes #

Fix docs test

---

README.md
nas.yml
roles/claper/defaults/main.yml
roles/claper/docs/claper.md
roles/claper/molecule/default/molecule.yml
roles/claper/molecule/default/side_effect.yml
roles/claper/molecule/default/verify.yml
roles/claper/molecule/default/verify_stopped.yml
roles/claper/tasks/main.yml
website/docs/applications/other/claper.md

Add claper

---

nas.yml
requirements.yml
roles/mergerfs/defaults/main.yml
roles/mergerfs/docs/mergerfs.md
roles/mergerfs/main/requirements.yml
roles/mergerfs/molecule/default/molecule.yml
roles/mergerfs/molecule/default/prepare.yml
roles/mergerfs/molecule/default/side_effect.yml
roles/mergerfs/molecule/default/verify.yml
roles/mergerfs/molecule/default/verify_stopped.yml
roles/mergerfs/tasks/main.yml
roles/mergerfs/templates/mergerfs.service.j2
website/docs/applications/system-tools/mergerfs.md

Add Mergerfs. Please see role docs for details.
Fixes #

✨ Add mergerfs

---

roles/rclone/defaults/main.yml
roles/rclone/docs/rclone.md
roles/rclone/molecule/default/molecule.yml
roles/rclone/molecule/default/side_effect.yml
roles/rclone/molecule/default/verify.yml
roles/rclone/molecule/default/verify_stopped.yml
roles/rclone/tasks/main.yml
roles/rclone/templates/cloud_upload.sh
roles/rclone/templates/excludes
website/docs/applications/system-tools/rclone.md

Adding cloud upload script that together with Rclone and Mergerfs (inspired by https://github.com/animosity22/homescripts)
Fixes #

✨ Add cloud upload script to Rclone/Mergerfs

---

README.md
nas.yml
roles/flarum/defaults/main.yml
roles/flarum/docs/flarum.md
roles/flarum/molecule/default/molecule.yml
roles/flarum/molecule/default/side_effect.yml
roles/flarum/molecule/default/verify.yml
roles/flarum/molecule/default/verify_stopped.yml
roles/flarum/tasks/main.yml
website/docs/applications/other/flarum.md

Add Flarum - self-hosted forum.
Fixes #

✨ Add Flarum

---

README.md
nas.yml
roles/frigate/defaults/main.yml
roles/frigate/docs/frigate.md
roles/frigate/molecule/default/molecule.yml
roles/frigate/molecule/default/side_effect.yml
roles/frigate/molecule/default/verify.yml
roles/frigate/molecule/default/verify_stopped.yml
roles/frigate/tasks/main.yml
roles/frigate/templates/config.yml.j2
website/docs/applications/home-automation/frigate.md

✨ Add Frigate NVR

---

README.md
nas.yml
roles/gaps/defaults/main.yml
roles/gaps/docs/gaps.md
roles/gaps/molecule/default/molecule.yml
roles/gaps/molecule/default/side_effect.yml
roles/gaps/molecule/default/verify.yml
roles/gaps/molecule/default/verify_stopped.yml
roles/gaps/tasks/main.yml
website/docs/applications/media-serving/gaps.md

Add Gaps to scan your plex library for missing items.
Fixes #

✨ Add Gaps

---

README.md
nas.yml
roles/ghost/defaults/main.yml
roles/ghost/docs/ghost.md
roles/ghost/molecule/default/molecule.yml
roles/ghost/molecule/default/side_effect.yml
roles/ghost/molecule/default/verify.yml
roles/ghost/molecule/default/verify_stopped.yml
roles/ghost/tasks/main.yml
website/docs/applications/content-management/ghost.md

✨ Add Ghost CMS

---

README.md
nas.yml
roles/graylog/defaults/main.yml
roles/graylog/docs/graylog.md
roles/graylog/molecule/default/molecule.yml
roles/graylog/molecule/default/side_effect.yml
roles/graylog/molecule/default/verify.yml
roles/graylog/molecule/default/verify_stopped.yml
roles/graylog/tasks/main.yml
website/docs/applications/monitoring/graylog.md

:sparkles: Add Graylog

---

README.md
nas.yml
roles/huginn/defaults/main.yml
roles/huginn/docs/huginn.md
roles/huginn/molecule/default/molecule.yml
roles/huginn/molecule/default/side_effect.yml
roles/huginn/molecule/default/verify.yml
roles/huginn/molecule/default/verify_stopped.yml
roles/huginn/tasks/main.yml
website/docs/applications/other/huginn.md

✨ Add Huginn

---

README.md
nas.yml
roles/kavita/defaults/main.yml
roles/kavita/docs/kavita.md
roles/kavita/molecule/default/molecule.yml
roles/kavita/molecule/default/side_effect.yml
roles/kavita/molecule/default/verify.yml
roles/kavita/molecule/default/verify_stopped.yml
roles/kavita/tasks/main.yml
website/docs/applications/media-serving/kavita.md

:sparkles: Add Kavita

---

README.md
nas.yml
roles/keycloak/defaults/main.yml
roles/keycloak/docs/keycloak.md
roles/keycloak/molecule/default/molecule.yml
roles/keycloak/molecule/default/side_effect.yml
roles/keycloak/molecule/default/verify.yml
roles/keycloak/molecule/default/verify_stopped.yml
roles/keycloak/tasks/main.yml
website/docs/applications/other/keycloak.md

:sparkles: Add Keycloak

---

README.md
nas.yml
roles/lazylibrarian/defaults/main.yml
roles/lazylibrarian/docs/lazylibrarian.md
roles/lazylibrarian/molecule/default/molecule.yml
roles/lazylibrarian/molecule/default/side_effect.yml
roles/lazylibrarian/molecule/default/verify.yml
roles/lazylibrarian/molecule/default/verify_stopped.yml
roles/lazylibrarian/tasks/main.yml
website/docs/applications/download-tools/lazylibrarian.md

:sparkles: Add LazyLibrarian

---

README.md
nas.yml
roles/librephotos/defaults/main.yml
roles/librephotos/docs/librephotos.md
roles/librephotos/molecule/default/molecule.yml
roles/librephotos/molecule/default/side_effect.yml
roles/librephotos/molecule/default/verify.yml
roles/librephotos/molecule/default/verify_stopped.yml
roles/librephotos/tasks/main.yml
website/docs/applications/other/librephotos.md

:sparkles: Add Librephotos

---

README.md
nas.yml
roles/libreddit/defaults/main.yml
roles/libreddit/docs/libreddit.md
roles/libreddit/molecule/default/molecule.yml
roles/libreddit/molecule/default/side_effect.yml
roles/libreddit/molecule/default/verify.yml
roles/libreddit/molecule/default/verify_stopped.yml
roles/libreddit/tasks/main.yml
website/docs/applications/news/libreddit.md

:sparkles: Add Libreddit

---

README.md
nas.yml
roles/phpmyadmin/defaults/main.yml
roles/phpmyadmin/docs/phpmyadmin.md
roles/phpmyadmin/molecule/default/molecule.yml
roles/phpmyadmin/molecule/default/side_effect.yml
roles/phpmyadmin/molecule/default/verify.yml
roles/phpmyadmin/molecule/default/verify_stopped.yml
roles/phpmyadmin/tasks/main.yml
roles/phpmyadmin/templates/config.inc.php
website/docs/applications/system-tools/phpmyadmin.md

:sparkles: Add phpMyAdmin

---

README.md
nas.yml
roles/mysql/defaults/main.yml
roles/mysql/docs/mysql.md
roles/mysql/molecule/default/molecule.yml
roles/mysql/molecule/default/side_effect.yml
roles/mysql/molecule/default/verify.yml
roles/mysql/molecule/default/verify_stopped.yml
roles/mysql/tasks/main.yml
website/docs/applications/system-tools/mysql.md

:sparkles: Add Mysql/MariaDB

---

README.md
nas.yml
roles/memos/defaults/main.yml
roles/memos/docs/memos.md
roles/memos/molecule/default/molecule.yml
roles/memos/molecule/default/side_effect.yml
roles/memos/molecule/default/verify.yml
roles/memos/molecule/default/verify_stopped.yml
roles/memos/tasks/main.yml
website/docs/applications/content-management/memos.md

:sparkles: Add memos

---

README.md
roles/stats/defaults/main.yml
roles/stats/docs/stats.md
roles/stats/files/loki/loki-config.yaml
roles/stats/molecule/default/molecule.yml
roles/stats/molecule/default/verify.yml
roles/stats/molecule/default/verify_stopped.yml
roles/stats/tasks/exporters.yml
roles/stats/tasks/grafana.yml
roles/stats/tasks/influxdb.yml
roles/stats/tasks/loki.yml
roles/stats/tasks/main.yml
roles/stats/tasks/prometheus.yml
roles/stats/tasks/telegraf.yml
roles/stats/templates/datasources/ansible-nas.yml.j2
roles/stats/templates/promtail-config.yaml.j2
website/docs/applications/monitoring/stats.md

Added Loki and Promtail as options to stats role.
Fixes #

:sparkles: Add Loki to Stats

---

README.md
nas.yml
roles/mattermost/defaults/main.yml
roles/mattermost/docs/mattermost.md
roles/mattermost/molecule/default/molecule.yml
roles/mattermost/molecule/default/side_effect.yml
roles/mattermost/molecule/default/verify.yml
roles/mattermost/molecule/default/verify_stopped.yml
roles/mattermost/tasks/main.yml
website/docs/applications/other/mattermost.md

:sparkles: Add Mattermost

---

README.md
nas.yml
roles/minetest-server/defaults/main.yml
roles/minetest-server/docs/minetest-server.md
roles/minetest-server/molecule/default/molecule.yml
roles/minetest-server/molecule/default/side_effect.yml
roles/minetest-server/molecule/default/verify.yml
roles/minetest-server/molecule/default/verify_stopped.yml
roles/minetest-server/tasks/main.yml
roles/minetest-server/templates/minetest.conf.j2
website/docs/applications/gaming/minetest-server.md

:sparkles: Add Minetest Server

---

README.md
nas.yml
roles/moviematch/defaults/main.yml
roles/moviematch/docs/moviematch.md
roles/moviematch/molecule/default/molecule.yml
roles/moviematch/molecule/default/side_effect.yml
roles/moviematch/molecule/default/verify.yml
roles/moviematch/molecule/default/verify_stopped.yml
roles/moviematch/tasks/main.yml
website/docs/applications/media-serving/moviematch.md

:sparkles: Add MovieMatch

---

README.md
nas.yml
roles/nodered/defaults/main.yml
roles/nodered/docs/nodered.md
roles/nodered/molecule/default/molecule.yml
roles/nodered/molecule/default/side_effect.yml
roles/nodered/molecule/default/verify.yml
roles/nodered/molecule/default/verify_stopped.yml
roles/nodered/tasks/main.yml
website/docs/applications/home-automation/nodered.md

:sparkles: Add Node-RED

---

README.md
nas.yml
roles/nzbhydra2/defaults/main.yml
roles/nzbhydra2/docs/nzbhydra2.md
roles/nzbhydra2/molecule/default/molecule.yml
roles/nzbhydra2/molecule/default/side_effect.yml
roles/nzbhydra2/molecule/default/verify.yml
roles/nzbhydra2/molecule/default/verify_stopped.yml
roles/nzbhydra2/tasks/main.yml
website/docs/applications/download-tools/nzbhydra2.md

:sparkles: Add Nzbhydra2

---

README.md
nas.yml
roles/photofield/defaults/main.yml
roles/photofield/docs/photofield.md
roles/photofield/files/configuration.yaml
roles/photofield/molecule/default/molecule.yml
roles/photofield/molecule/default/side_effect.yml
roles/photofield/molecule/default/verify.yml
roles/photofield/molecule/default/verify_stopped.yml
roles/photofield/tasks/main.yml
website/docs/applications/other/photofield.md

:sparkles: Add Photofield

---

README.md
nas.yml
roles/photoprism/defaults/main.yml
roles/photoprism/docs/photoprism.md
roles/photoprism/files/configuration.yaml
roles/photoprism/molecule/default/molecule.yml
roles/photoprism/molecule/default/side_effect.yml
roles/photoprism/molecule/default/verify.yml
roles/photoprism/molecule/default/verify_stopped.yml
roles/photoprism/tasks/main.yml
website/docs/applications/other/photoprism.md

:sparkles: Add PhotoPrism

---

README.md
nas.yml
roles/photostructure/defaults/main.yml
roles/photostructure/docs/photostructure.md
roles/photostructure/molecule/default/molecule.yml
roles/photostructure/molecule/default/side_effect.yml
roles/photostructure/molecule/default/verify.yml
roles/photostructure/molecule/default/verify_stopped.yml
roles/photostructure/tasks/main.yml
website/docs/applications/other/photostructure.md

:sparkles: Add PhotoStructure

---

README.md
nas.yml
roles/plex/defaults/main.yml
roles/plex/docs/plex.md
roles/plex/molecule/default/molecule.yml
roles/plex/molecule/default/side_effect.yml
roles/plex/molecule/default/verify.yml
roles/plex/molecule/default/verify_stopped.yml
roles/plex/tasks/main.yml
roles/plex/templates/autoscan_config.yml.j2

Adds Plex Autoscan to Plex
Fixes #

:sparkles: Add Plex Autoscan as an option to Plex

---

roles/plex/defaults/main.yml
roles/plex/docs/plex.md
roles/plex/molecule/default/molecule.yml
roles/plex/molecule/default/side_effect.yml
roles/plex/molecule/default/verify.yml
roles/plex/molecule/default/verify_stopped.yml
roles/plex/tasks/main.yml
roles/plex/templates/pmm_config.yml.j2
website/docs/applications/media-serving/plex.md

Adds Plex Meta Manager
Fixes #

:sparkles: Add Plex Meta Manager

---

README.md
nas.yml
roles/releasebell/defaults/main.yml
roles/releasebell/docs/releasebell.md
roles/releasebell/molecule/default/molecule.yml
roles/releasebell/molecule/default/side_effect.yml
roles/releasebell/molecule/default/verify.yml
roles/releasebell/molecule/default/verify_stopped.yml
roles/releasebell/tasks/main.yml
roles/releasebell/templates/users.json.j2
website/docs/applications/other/releasebell.md

:sparkles: Add Releasebell

---

README.md
nas.yml
requirements.yml
roles/restic/defaults/main.yml
roles/restic/docs/restic.md
roles/restic/main/requirements.yml
roles/restic/molecule/default/molecule.yml
roles/restic/molecule/default/side_effect.yml
roles/restic/molecule/default/verify.yml
roles/restic/molecule/default/verify_stopped.yml
roles/restic/tasks/main.yml
roles/restic/templates/restic_access_Linux.j2
roles/restic/templates/restic_script_Linux.j2
website/docs/applications/system-tools/restic.md

:sparkles: Add Restic

---

README.md
nas.yml
roles/seafile/defaults/main.yml
roles/seafile/docs/seafile.md
roles/seafile/molecule/default/molecule.yml
roles/seafile/molecule/default/side_effect.yml
roles/seafile/molecule/default/verify.yml
roles/seafile/molecule/default/verify_stopped.yml
roles/seafile/tasks/main.yml
website/docs/applications/other/seafile.md

:sparkles: Add Seafile

---

roles/restic/molecule/default/molecule.yml
roles/restic/molecule/default/prepare.yml

Fixes Restic Integration workflow on Github

:bug: Fix restic integration workflow on Github

---

README.md
nas.yml
roles/shaarli/defaults/main.yml
roles/shaarli/docs/shaarli.md
roles/shaarli/molecule/default/molecule.yml
roles/shaarli/molecule/default/side_effect.yml
roles/shaarli/molecule/default/verify.yml
roles/shaarli/molecule/default/verify_stopped.yml
roles/shaarli/tasks/main.yml
website/docs/applications/other/shaarli.md

:sparkles: Add Shaarli

---

README.md
nas.yml
roles/snipeit/defaults/main.yml
roles/snipeit/docs/snipeit.md
roles/snipeit/molecule/default/molecule.yml
roles/snipeit/molecule/default/side_effect.yml
roles/snipeit/molecule/default/verify.yml
roles/snipeit/molecule/default/verify_stopped.yml
roles/snipeit/tasks/main.yml
website/docs/applications/system-tools/snipeit.md

:sparkles: Add Snipe-IT

---

README.md
nas.yml
roles/trilium/defaults/main.yml
roles/trilium/docs/trilium.md
roles/trilium/molecule/default/molecule.yml
roles/trilium/molecule/default/side_effect.yml
roles/trilium/molecule/default/verify.yml
roles/trilium/molecule/default/verify_stopped.yml
roles/trilium/tasks/main.yml
website/docs/applications/content-management/trilium.md

:sparkles: Add Trilium

---

README.md
nas.yml
roles/ttrss/defaults/main.yml
roles/ttrss/docs/ttrss.md
roles/ttrss/molecule/default/molecule.yml
roles/ttrss/molecule/default/side_effect.yml
roles/ttrss/molecule/default/verify.yml
roles/ttrss/molecule/default/verify_stopped.yml
roles/ttrss/tasks/main.yml
website/docs/applications/news/ttrss.md

:sparkles: Add Tt-rss

---

README.md
nas.yml
roles/webtrees/defaults/main.yml
roles/webtrees/docs/webtrees.md
roles/webtrees/molecule/default/molecule.yml
roles/webtrees/molecule/default/side_effect.yml
roles/webtrees/molecule/default/verify.yml
roles/webtrees/molecule/default/verify_stopped.yml
roles/webtrees/tasks/main.yml
website/docs/applications/other/webtrees.md

:sparkles: Add webtrees

---

README.md
nas.yml
roles/wger/defaults/main.yml
roles/wger/docs/wger.md
roles/wger/molecule/default/molecule.yml
roles/wger/molecule/default/side_effect.yml
roles/wger/molecule/default/verify.yml
roles/wger/molecule/default/verify_stopped.yml
roles/wger/tasks/main.yml
roles/wger/templates/nginx.conf
website/docs/applications/other/wger.md

:sparkles: Add Wger

---

README.md
nas.yml
roles/whoogle/defaults/main.yml
roles/whoogle/docs/whoogle.md
roles/whoogle/molecule/default/molecule.yml
roles/whoogle/molecule/default/side_effect.yml
roles/whoogle/molecule/default/verify.yml
roles/whoogle/molecule/default/verify_stopped.yml
roles/whoogle/tasks/main.yml
website/docs/applications/other/whoogle.md

:sparkles: Add Whoogle

---

README.md
nas.yml
roles/changedetection/defaults/main.yml
roles/changedetection/docs/changedetection.md
roles/changedetection/molecule/default/molecule.yml
roles/changedetection/molecule/default/side_effect.yml
roles/changedetection/molecule/default/verify.yml
roles/changedetection/molecule/default/verify_stopped.yml
roles/changedetection/tasks/main.yml
website/docs/applications/other/changedetection.md

Adds changedetection.io
Fixes #

:sparkles: Add Changedetection.io

---

README.md
nas.yml
roles/huntly/defaults/main.yml
roles/huntly/docs/huntly.md
roles/huntly/molecule/default/molecule.yml
roles/huntly/molecule/default/side_effect.yml
roles/huntly/molecule/default/verify.yml
roles/huntly/molecule/default/verify_stopped.yml
roles/huntly/tasks/main.yml
website/docs/applications/content-management/huntly.md

:sparkles: Add Huntly

---

README.md
nas.yml
roles/wishthis/defaults/main.yml
roles/wishthis/docs/wishthis.md
roles/wishthis/files/config-sample.php
roles/wishthis/molecule/default/molecule.yml
roles/wishthis/molecule/default/side_effect.yml
roles/wishthis/molecule/default/verify.yml
roles/wishthis/molecule/default/verify_stopped.yml
roles/wishthis/tasks/main.yml
roles/wishthis/templates/config.php.j2
website/docs/applications/other/wishthis.md

:sparkles: Add Wishthis

---

roles/nomad/tasks/main.yml

Merge upstream

---

README.md
nas.yml
roles/listmonk/defaults/main.yml
roles/listmonk/docs/listmonk.md
roles/listmonk/molecule/default/molecule.yml
roles/listmonk/molecule/default/side_effect.yml
roles/listmonk/molecule/default/verify.yml
roles/listmonk/molecule/default/verify_stopped.yml
roles/listmonk/tasks/main.yml
roles/listmonk/templates/config.toml.j2
website/docs/applications/other/listmonk.md

:sparkles: Add listmonk

---

README.md
nas.yml
roles/littlelink/defaults/main.yml
roles/littlelink/docs/littlelink.md
roles/littlelink/molecule/default/molecule.yml
roles/littlelink/molecule/default/side_effect.yml
roles/littlelink/molecule/default/verify.yml
roles/littlelink/molecule/default/verify_stopped.yml
roles/littlelink/tasks/main.yml
website/docs/applications/other/littlelink.md

Adds littlelink-server
Fixes #

:sparkles: Add littlelink-server

---

README.md
nas.yml
roles/whatsupdocker/defaults/main.yml
roles/whatsupdocker/docs/whatsupdocker.md
roles/whatsupdocker/molecule/default/molecule.yml
roles/whatsupdocker/molecule/default/side_effect.yml
roles/whatsupdocker/molecule/default/verify.yml
roles/whatsupdocker/molecule/default/verify_stopped.yml
roles/whatsupdocker/tasks/main.yml
website/docs/applications/system-tools/whatsupdocker.md

:sparkles: Add Whats-up-Docker

---

README.md
nas.yml
roles/flatnotes/defaults/main.yml
roles/flatnotes/docs/flatnotes.md
roles/flatnotes/molecule/default/molecule.yml
roles/flatnotes/molecule/default/side_effect.yml
roles/flatnotes/molecule/default/verify.yml
roles/flatnotes/molecule/default/verify_stopped.yml
roles/flatnotes/tasks/main.yml
website/docs/applications/content-management/flatnotes.md

:sparkles: Add Flatnotes

---

README.md
nas.yml
roles/excalidraw/defaults/main.yml
roles/excalidraw/docs/exaclidraw.md
roles/excalidraw/molecule/default/molecule.yml
roles/excalidraw/molecule/default/side_effect.yml
roles/excalidraw/molecule/default/verify.yml
roles/excalidraw/molecule/default/verify_stopped.yml
roles/excalidraw/tasks/main.yml
website/docs/applications/other/exaclidraw.md

:sparkles: Add Excalidraw

---

README.md
nas.yml
roles/chatpad/defaults/main.yml
roles/chatpad/docs/chatpad.md
roles/chatpad/molecule/default/molecule.yml
roles/chatpad/molecule/default/side_effect.yml
roles/chatpad/molecule/default/verify.yml
roles/chatpad/molecule/default/verify_stopped.yml
roles/chatpad/tasks/main.yml
website/docs/applications/other/chatpad.md

:sparkles: Add Chatpad

---

README.md
nas.yml
roles/miniserve/defaults/main.yml
roles/miniserve/docs/miniserve.md
roles/miniserve/molecule/default/molecule.yml
roles/miniserve/molecule/default/side_effect.yml
roles/miniserve/molecule/default/verify.yml
roles/miniserve/molecule/default/verify_stopped.yml
roles/miniserve/tasks/main.yml
website/docs/applications/other/miniserve.md

:sparkles: Add miniserve

---

README.md
nas.yml
roles/dufs/defaults/main.yml
roles/dufs/docs/dufs.md
roles/dufs/molecule/default/molecule.yml
roles/dufs/molecule/default/side_effect.yml
roles/dufs/molecule/default/verify.yml
roles/dufs/molecule/default/verify_stopped.yml
roles/dufs/tasks/main.yml
website/docs/applications/other/dufs.md

:sparkles: Add dufs

---

roles/firefly/defaults/main.yml
roles/firefly/molecule/default/molecule.yml
roles/firefly/molecule/default/verify.yml
roles/firefly/molecule/default/verify_stopped.yml
roles/firefly/tasks/main.yml
website/docs/applications/other/firefly.md

Adds Firefly Data Importer to Firefly
Fixes #

:sparkles: Add Firefly Data Importer

---

README.md
nas.yml
roles/icbinv/defaults/main.yml
roles/icbinv/docs/icbinv.md
roles/icbinv/molecule/default/molecule.yml
roles/icbinv/molecule/default/side_effect.yml
roles/icbinv/molecule/default/verify.yml
roles/icbinv/molecule/default/verify_stopped.yml
roles/icbinv/tasks/main.yml
roles/icbinv/templates/config.json.j2
website/docs/applications/home-automation/icbinv.md

Adds I Can't Belileve Its Not Valetudo
Fixes #

:sparkles: Add I Can't Believe Its Not Valetudo

---

README.md
nas.yml
roles/invidious/defaults/main.yml
roles/invidious/docs/invidious.md
roles/invidious/molecule/default/molecule.yml
roles/invidious/molecule/default/side_effect.yml
roles/invidious/molecule/default/verify.yml
roles/invidious/molecule/default/verify_stopped.yml
roles/invidious/tasks/main.yml
website/docs/applications/media-serving/invidious.md

:sparkles: Add Invidious

---

roles/phpmyadmin/molecule/default/molecule.yml

Fixes #
Fixes failing integration test - phpmyadmin molecule tests.

✅ Fix phpmyadmin

---

README.md
nas.yml
roles/leantime/defaults/main.yml
roles/leantime/docs/leantime.md
roles/leantime/molecule/default/molecule.yml
roles/leantime/molecule/default/side_effect.yml
roles/leantime/molecule/default/verify.yml
roles/leantime/molecule/default/verify_stopped.yml
roles/leantime/tasks/main.yml
website/docs/applications/development-tools/leantime.md

:sparkles: Add Leantime

---

README.md
nas.yml
roles/commafeed/defaults/main.yml
roles/commafeed/docs/commafeed.md
roles/commafeed/molecule/default/molecule.yml
roles/commafeed/molecule/default/side_effect.yml
roles/commafeed/molecule/default/verify.yml
roles/commafeed/molecule/default/verify_stopped.yml
roles/commafeed/tasks/main.yml
website/docs/applications/news/commafeed.md

:sparkles: Add CommaFeed

---

README.md
nas.yml
roles/ebusd/defaults/main.yml
roles/ebusd/docs/ebusd.md
roles/ebusd/molecule/default/molecule.yml
roles/ebusd/molecule/default/side_effect.yml
roles/ebusd/molecule/default/verify.yml
roles/ebusd/molecule/default/verify_stopped.yml
roles/ebusd/tasks/main.yml
website/docs/applications/home-automation/ebusd.md

:sparkles: Add ebusd

---

README.md
nas.yml
roles/stirlingpdf/defaults/main.yml
roles/stirlingpdf/docs/stirlingpdf.md
roles/stirlingpdf/molecule/default/molecule.yml
roles/stirlingpdf/molecule/default/side_effect.yml
roles/stirlingpdf/molecule/default/verify.yml
roles/stirlingpdf/molecule/default/verify_stopped.yml
roles/stirlingpdf/tasks/main.yml
website/docs/applications/other/stirlingpdf.md

:sparkles: Add Stirling-PDF

---

README.md
nas.yml
roles/openbooks/defaults/main.yml
roles/openbooks/docs/openbooks.md
roles/openbooks/molecule/default/molecule.yml
roles/openbooks/molecule/default/side_effect.yml
roles/openbooks/molecule/default/verify.yml
roles/openbooks/molecule/default/verify_stopped.yml
roles/openbooks/tasks/main.yml
website/docs/applications/other/openbooks.md

:sparkles: Add Openbooks

---

README.md
nas.yml
roles/servas/defaults/main.yml
roles/servas/docs/servas.md
roles/servas/molecule/default/molecule.yml
roles/servas/molecule/default/side_effect.yml
roles/servas/molecule/default/verify.yml
roles/servas/molecule/default/verify_stopped.yml
roles/servas/tasks/main.yml
website/docs/applications/content-management/servas.md

:sparkles: Add Servas

---

README.md
nas.yml
roles/linkwarden/defaults/main.yml
roles/linkwarden/docs/linkwarden.md
roles/linkwarden/molecule/default/molecule.yml
roles/linkwarden/molecule/default/side_effect.yml
roles/linkwarden/molecule/default/verify.yml
roles/linkwarden/molecule/default/verify_stopped.yml
roles/linkwarden/tasks/main.yml
website/docs/applications/other/linkwarden.md

:sparkles: Add Linkwarden

---

README.md
nas.yml
roles/standardnotes/defaults/main.yml
roles/standardnotes/docs/standardnotes.md
roles/standardnotes/molecule/default/molecule.yml
roles/standardnotes/molecule/default/side_effect.yml
roles/standardnotes/molecule/default/verify.yml
roles/standardnotes/molecule/default/verify_stopped.yml
roles/standardnotes/tasks/main.yml
website/docs/applications/content-management/standardnotes.md

:sparkles: Add Standard Notes

---

README.md
nas.yml
roles/dockge/defaults/main.yml
roles/dockge/docs/dockge.md
roles/dockge/molecule/default/molecule.yml
roles/dockge/molecule/default/side_effect.yml
roles/dockge/molecule/default/verify.yml
roles/dockge/molecule/default/verify_stopped.yml
roles/dockge/tasks/main.yml
website/docs/applications/system-tools/dockge.md

:sparkles: Add Dockge

---

README.md
nas.yml
roles/activepieces/defaults/main.yml
roles/activepieces/docs/activepieces.md
roles/activepieces/molecule/default/molecule.yml
roles/activepieces/molecule/default/side_effect.yml
roles/activepieces/molecule/default/verify.yml
roles/activepieces/molecule/default/verify_stopped.yml
roles/activepieces/tasks/main.yml
website/docs/applications/other/activepieces.md

:sparkles: Add Activepieces

---

README.md
nas.yml
roles/ryot/defaults/main.yml
roles/ryot/docs/ryot.md
roles/ryot/molecule/default/molecule.yml
roles/ryot/molecule/default/side_effect.yml
roles/ryot/molecule/default/verify.yml
roles/ryot/molecule/default/verify_stopped.yml
roles/ryot/tasks/main.yml
website/docs/applications/content-management/ryot.md

:sparkles: Add Ryot

---

README.md
nas.yml
roles/lldap/defaults/main.yml
roles/lldap/docs/lldap.md
roles/lldap/molecule/default/molecule.yml
roles/lldap/molecule/default/side_effect.yml
roles/lldap/molecule/default/verify.yml
roles/lldap/molecule/default/verify_stopped.yml
roles/lldap/tasks/main.yml
website/docs/applications/system-tools/lldap.md

:sparkles: Add LLdap

---

README.md
nas.yml
roles/hafusion/defaults/main.yml
roles/hafusion/docs/hafusion.md
roles/hafusion/molecule/default/molecule.yml
roles/hafusion/molecule/default/side_effect.yml
roles/hafusion/molecule/default/verify.yml
roles/hafusion/molecule/default/verify_stopped.yml
roles/hafusion/tasks/main.yml
website/docs/applications/home-automation/hafusion.md

:sparkles: Adds HA Fusion

---

README.md
nas.yml
roles/libretranslate/defaults/main.yml
roles/libretranslate/docs/libretranslate.md
roles/libretranslate/molecule/default/molecule.yml
roles/libretranslate/molecule/default/side_effect.yml
roles/libretranslate/molecule/default/verify.yml
roles/libretranslate/molecule/default/verify_stopped.yml
roles/libretranslate/tasks/main.yml
website/docs/applications/other/libretranslate.md

:sparkles: Add LibreTranslate

---

.github/workflows/ci.yml
.github/workflows/docs-deploy.yml
.github/workflows/docs-test.yml
README.md
nas.yml
roles/threadfin/defaults/main.yml
roles/threadfin/molecule/default/molecule.yml
roles/threadfin/molecule/default/side_effect.yml
roles/threadfin/molecule/default/verify.yml
roles/threadfin/molecule/default/verify_stopped.yml
roles/threadfin/tasks/main.yml
tests/github-test-matrix.sh
website/docs/applications/media-serving/threadfin.md

🔀 Pull upstream

---

README.md
nas.yml
roles/outline/defaults/main.yml
roles/outline/docs/outline.md
roles/outline/molecule/default/molecule.yml
roles/outline/molecule/default/side_effect.yml
roles/outline/molecule/default/verify.yml
roles/outline/molecule/default/verify_stopped.yml
roles/outline/requirements.yml
roles/outline/tasks/main.yml
website/docs/applications/content-management/outline.md

✨ Add outline

---

README.md
nas.yml
roles/obsidian/defaults/main.yml
roles/obsidian/docs/obisidian.md
roles/obsidian/molecule/default/molecule.yml
roles/obsidian/molecule/default/side_effect.yml
roles/obsidian/molecule/default/verify.yml
roles/obsidian/molecule/default/verify_stopped.yml
roles/obsidian/requirements.yml
roles/obsidian/tasks/main.yml
website/docs/applications/content-management/obsidian.md

:sparkles: Add Obsidian

---

README.md
nas.yml
roles/siyuan/defaults/main.yml
roles/siyuan/docs/siyuan.md
roles/siyuan/molecule/default/molecule.yml
roles/siyuan/molecule/default/side_effect.yml
roles/siyuan/molecule/default/verify.yml
roles/siyuan/molecule/default/verify_stopped.yml
roles/siyuan/requirements.yml
roles/siyuan/tasks/main.yml
website/docs/applications/content-management/siyuan.md

:sparkles: Add SiYuan

---

README.md
nas.yml
roles/affine/defaults/main.yml
roles/affine/docs/affine.md
roles/affine/molecule/default/molecule.yml
roles/affine/molecule/default/side_effect.yml
roles/affine/molecule/default/verify.yml
roles/affine/molecule/default/verify_stopped.yml
roles/affine/requirements.yml
roles/affine/tasks/main.yml
website/docs/applications/content-management/affine.md

:sparkles: Add Affine

---

README.md
nas.yml
roles/open-resume/defaults/main.yml
roles/open-resume/docs/openresume.md
roles/open-resume/molecule/default/molecule.yml
roles/open-resume/molecule/default/side_effect.yml
roles/open-resume/molecule/default/verify.yml
roles/open-resume/molecule/default/verify_stopped.yml
roles/open-resume/requirements.yml
roles/open-resume/tasks/main.yml
website/docs/applications/other/openresume.md

:sparkles: Add Open-resume

---

roles/deluge/tasks/main.yml
roles/jellyfin/tasks/main.yml
roles/nextcloud/tasks/main.yml

Pull upstream

---

README.md
nas.yml
roles/rallly/defaults/main.yml
roles/rallly/docs/rallly.md
roles/rallly/molecule/default/molecule.yml
roles/rallly/molecule/default/side_effect.yml
roles/rallly/molecule/default/verify.yml
roles/rallly/molecule/default/verify_stopped.yml
roles/rallly/requirements.yml
roles/rallly/tasks/main.yml
website/docs/applications/other/rallly.md

:sparkles: Add Rallly

---

README.md
nas.yml
roles/metube/defaults/main.yml
roles/metube/docs/metube.md
roles/metube/molecule/default/molecule.yml
roles/metube/molecule/default/side_effect.yml
roles/metube/molecule/default/verify.yml
roles/metube/molecule/default/verify_stopped.yml
roles/metube/requirements.yml
roles/metube/tasks/main.yml
website/docs/applications/download-tools/metube.md

:sparkles: Add MeTube

---

README.md
nas.yml
roles/homarr/defaults/main.yml
roles/homarr/docs/homarr.md
roles/homarr/molecule/default/molecule.yml
roles/homarr/molecule/default/side_effect.yml
roles/homarr/molecule/default/verify.yml
roles/homarr/molecule/default/verify_stopped.yml
roles/homarr/requirements.yml
roles/homarr/tasks/main.yml
website/docs/applications/dashboards/homarr.md

:sparkles: Add Homarr

---

README.md
nas.yml
roles/neko/defaults/main.yml
roles/neko/docs/neko.md
roles/neko/molecule/default/molecule.yml
roles/neko/molecule/default/side_effect.yml
roles/neko/molecule/default/verify.yml
roles/neko/molecule/default/verify_stopped.yml
roles/neko/requirements.yml
roles/neko/tasks/main.yml
website/docs/applications/other/neko.md

:sparkles: Add n.eko

---

README.md
nas.yml
roles/tooljet/defaults/main.yml
roles/tooljet/docs/tooljet.md
roles/tooljet/molecule/default/molecule.yml
roles/tooljet/molecule/default/side_effect.yml
roles/tooljet/molecule/default/verify.yml
roles/tooljet/molecule/default/verify_stopped.yml
roles/tooljet/requirements.yml
roles/tooljet/tasks/main.yml
website/docs/applications/development-tools/tooljet.md

:sparkles: Add ToolJet

---

README.md
nas.yml
roles/formio/defaults/main.yml
roles/formio/docs/formio.md
roles/formio/molecule/default/molecule.yml
roles/formio/molecule/default/side_effect.yml
roles/formio/molecule/default/verify.yml
roles/formio/molecule/default/verify_stopped.yml
roles/formio/requirements.yml
roles/formio/tasks/main.yml
website/docs/applications/other/formio.md

:sparkles: Add FormIO

---

README.md
nas.yml
roles/input/defaults/main.yml
roles/input/docs/input.md
roles/input/molecule/default/molecule.yml
roles/input/molecule/default/side_effect.yml
roles/input/molecule/default/verify.yml
roles/input/molecule/default/verify_stopped.yml
roles/input/requirements.yml
roles/input/tasks/main.yml
website/docs/applications/other/input.md

:sparkles: Add Input

---

README.md
nas.yml
roles/livehelperchat/defaults/main.yml
roles/livehelperchat/docs/livehelperchat.md
roles/livehelperchat/molecule/default/molecule.yml
roles/livehelperchat/molecule/default/side_effect.yml
roles/livehelperchat/molecule/default/verify.yml
roles/livehelperchat/molecule/default/verify_stopped.yml
roles/livehelperchat/requirements.yml
roles/livehelperchat/tasks/main.yml
roles/livehelperchat/templates/nginx/mime.types
roles/livehelperchat/templates/nginx/nginx.conf
roles/livehelperchat/templates/nginx/site-nodejs.conf
roles/livehelperchat/templates/nginx/site-ssl.conf
roles/livehelperchat/templates/nginx/site.conf
roles/livehelperchat/templates/php-fpm/zz-lhc.conf
roles/livehelperchat/templates/scripts/phpresque.sh
roles/livehelperchat/templates/scripts/resque.sh
roles/livehelperchat/templates/scripts/transfer.sh
roles/livehelperchat/templates/scripts/webhook.sh
roles/livehelperchat/templates/scripts/workflow.sh
website/docs/applications/other/livehelperchat.md

:sparkles: Add LiveHelperChat

---

roles/chatwoot/molecule/default/verify.yml
roles/chatwoot/tasks/main.yml

:bug: Fix chatwoot

---

roles/livehelperchat/molecule/default/molecule.yml
roles/livehelperchat/molecule/default/prepare.yml

:bug: Fix livehelperchat

---

roles/livehelperchat/molecule/default/molecule.yml
roles/livehelperchat/molecule/default/prepare.yml
roles/livehelperchat/tasks/main.yml

Fix livehelperchat

---

README.md
nas.yml
roles/mantium/defaults/main.yml
roles/mantium/docs/mantium.md
roles/mantium/molecule/default/molecule.yml
roles/mantium/molecule/default/side_effect.yml
roles/mantium/molecule/default/verify.yml
roles/mantium/molecule/default/verify_stopped.yml
roles/mantium/requirements.yml
roles/mantium/tasks/main.yml
website/docs/applications/other/mantium.md

:sparkles: Add Mantium

---

README.md
nas.yml
roles/readeck/defaults/main.yml
roles/readeck/docs/readeck.md
roles/readeck/molecule/default/molecule.yml
roles/readeck/molecule/default/side_effect.yml
roles/readeck/molecule/default/verify.yml
roles/readeck/molecule/default/verify_stopped.yml
roles/readeck/requirements.yml
roles/readeck/tasks/main.yml
website/docs/applications/other/readeck.md

:sparkles: Add Readeck

---

README.md
nas.yml
roles/metabase/defaults/main.yml
roles/metabase/docs/metabase.md
roles/metabase/molecule/default/molecule.yml
roles/metabase/molecule/default/side_effect.yml
roles/metabase/molecule/default/verify.yml
roles/metabase/molecule/default/verify_stopped.yml
roles/metabase/requirements.yml
roles/metabase/tasks/main.yml
website/docs/applications/other/metabase.md

:sparkles: Add Metabase

---

README.md
nas.yml
roles/suitecrm/defaults/main.yml
roles/suitecrm/docs/suitecrm.md
roles/suitecrm/molecule/default/molecule.yml
roles/suitecrm/molecule/default/side_effect.yml
roles/suitecrm/molecule/default/verify.yml
roles/suitecrm/molecule/default/verify_stopped.yml
roles/suitecrm/requirements.yml
roles/suitecrm/tasks/main.yml
website/docs/applications/content-management/suitecrm.md

:sparkles: Add SuiteCRM

---

README.md
nas.yml
roles/espocrm/defaults/main.yml
roles/espocrm/docs/espocrm.md
roles/espocrm/molecule/default/molecule.yml
roles/espocrm/molecule/default/side_effect.yml
roles/espocrm/molecule/default/verify.yml
roles/espocrm/molecule/default/verify_stopped.yml
roles/espocrm/requirements.yml
roles/espocrm/tasks/main.yml
website/docs/applications/content-management/espocrm.md

:sparkles: Add EspoCRM

---

README.md
nas.yml
roles/uppy/defaults/main.yml
roles/uppy/docs/uppy.md
roles/uppy/molecule/default/molecule.yml
roles/uppy/molecule/default/side_effect.yml
roles/uppy/molecule/default/verify.yml
roles/uppy/molecule/default/verify_stopped.yml
roles/uppy/requirements.yml
roles/uppy/tasks/main.yml
website/docs/applications/other/uppy.md

:sparkles: Add Uppy

---

nas.yml
requirements.yml
roles/calibreweb/tasks/main.yml
roles/silverbullet/tasks/main.yml

Pull upstream changes

---

README.md
nas.yml
roles/appsmith/defaults/main.yml
roles/appsmith/docs/appsmith.md
roles/appsmith/molecule/default/molecule.yml
roles/appsmith/molecule/default/side_effect.yml
roles/appsmith/molecule/default/verify.yml
roles/appsmith/molecule/default/verify_stopped.yml
roles/appsmith/requirements.yml
roles/appsmith/tasks/main.yml
website/docs/applications/other/appsmith.md

:sparkles: Add Appsmith

---

README.md
nas.yml
roles/lowcoder/defaults/main.yml
roles/lowcoder/docs/lowcoder.md
roles/lowcoder/molecule/default/molecule.yml
roles/lowcoder/molecule/default/side_effect.yml
roles/lowcoder/molecule/default/verify.yml
roles/lowcoder/molecule/default/verify_stopped.yml
roles/lowcoder/requirements.yml
roles/lowcoder/tasks/main.yml
website/docs/applications/development-tools/lowcoder.md

:sparkles: Add Lowcoder

---

README.md
nas.yml
roles/aria2/defaults/main.yml
roles/aria2/docs/aria2.md
roles/aria2/molecule/default/molecule.yml
roles/aria2/molecule/default/side_effect.yml
roles/aria2/molecule/default/verify.yml
roles/aria2/molecule/default/verify_stopped.yml
roles/aria2/requirements.yml
roles/aria2/tasks/main.yml
website/docs/applications/download-tools/aria2.md

:sparkles: Add aria2

---

README.md
nas.yml
roles/rsshub/defaults/main.yml
roles/rsshub/docs/rsshub.md
roles/rsshub/molecule/default/molecule.yml
roles/rsshub/molecule/default/side_effect.yml
roles/rsshub/molecule/default/verify.yml
roles/rsshub/molecule/default/verify_stopped.yml
roles/rsshub/requirements.yml
roles/rsshub/tasks/main.yml
website/docs/applications/news/rsshub.md

:sparkles: Add RSSHub

---

README.md
nas.yml
roles/linkstack/defaults/main.yml
roles/linkstack/docs/linkstack.md
roles/linkstack/molecule/default/molecule.yml
roles/linkstack/molecule/default/side_effect.yml
roles/linkstack/molecule/default/verify.yml
roles/linkstack/molecule/default/verify_stopped.yml
roles/linkstack/requirements.yml
roles/linkstack/tasks/main.yml
website/docs/applications/other/linkstack.md

:sparkles: Add Linkstack

---

roles/suitecrm/molecule/default/molecule.yml

✅ Fix SuiteCRM tests

---

roles/immich/tasks/main.yml

Upgrades Immich to latest version
Fixes #

⬆️ Upgrade Immich to latest version

---

README.md
nas.yml
roles/unifi/defaults/main.yml
roles/unifi/docs/unifi.md
roles/unifi/molecule/default/molecule.yml
roles/unifi/molecule/default/side_effect.yml
roles/unifi/molecule/default/verify.yml
roles/unifi/molecule/default/verify_stopped.yml
roles/unifi/requirements.yml
roles/unifi/tasks/main.yml
roles/unifi/templates/init-mongo.js.j2
website/docs/applications/other/unifi.md

Adds Unifi Network Application
Fixes #

:sparkles: Add Unifi Network Application

---

requirements.yml

✅ Add crypto collection to requirements

---

README.md
nas.yml
roles/shiori/defaults/main.yml
roles/shiori/docs/shiori.md
roles/shiori/molecule/default/molecule.yml
roles/shiori/molecule/default/side_effect.yml
roles/shiori/molecule/default/verify.yml
roles/shiori/molecule/default/verify_stopped.yml
roles/shiori/requirements.yml
roles/shiori/tasks/main.yml
website/docs/applications/other/shiori.md

✨ Add Shiori

---

README.md
nas.yml
roles/hievents/defaults/main.yml
roles/hievents/docs/hievents.md
roles/hievents/molecule/default/molecule.yml
roles/hievents/molecule/default/side_effect.yml
roles/hievents/molecule/default/verify.yml
roles/hievents/molecule/default/verify_stopped.yml
roles/hievents/requirements.yml
roles/hievents/tasks/main.yml
roles/hievents/templates/nginx.conf.j2
website/docs/applications/other/hievents.md

:sparkles: Add Hi.Events

---

roles/squirrel/tasks/main.yml

Added a volume for the server to stay up to date to latest version of doker-compose file

Update main.yml of Squirrel Servers Manager

---

README.md
nas.yml
roles/adventure_log/defaults/main.yml
roles/adventure_log/molecule/default/molecule.yml
roles/adventure_log/molecule/default/side_effect.yml
roles/adventure_log/molecule/default/verify.yml
roles/adventure_log/molecule/default/verify_stopped.yml
roles/adventure_log/requirements.yml
roles/adventure_log/tasks/main.yml
website/docs/applications/other/adventure-log.md

:sparkles: Add Adventure Log

---

README.md
nas.yml
roles/simplelogin/defaults/main.yml
roles/simplelogin/files/postconf.sh
roles/simplelogin/molecule/default/molecule.yml
roles/simplelogin/molecule/default/side_effect.yml
roles/simplelogin/molecule/default/verify.yml
roles/simplelogin/molecule/default/verify_stopped.yml
roles/simplelogin/requirements.yml
roles/simplelogin/tasks/main.yml
roles/simplelogin/templates/main.cf.j2
roles/simplelogin/templates/pgsql-relay-domains.cf.j2
roles/simplelogin/templates/pgsql-transport-maps.cf.j2
website/docs/applications/other/simplelogin.md

✨ Add SimpleLogin

---

README.md
nas.yml
roles/glpi/defaults/main.yml
roles/glpi/molecule/default/molecule.yml
roles/glpi/molecule/default/side_effect.yml
roles/glpi/molecule/default/verify.yml
roles/glpi/molecule/default/verify_stopped.yml
roles/glpi/requirements.yml
roles/glpi/tasks/main.yml
website/docs/applications/system-tools/glpi.md

:sparkles: Add Glpi

---

README.md
group_vars/all.yml
nas.yml
roles/apcupsd/defaults/main.yml
roles/apcupsd/molecule/default/molecule.yml
roles/apcupsd/molecule/default/side_effect.yml
roles/apcupsd/molecule/default/verify.yml
roles/apcupsd/molecule/default/verify_stopped.yml
roles/apcupsd/requirements.yml
roles/apcupsd/tasks/main.yml
roles/apcupsd/templates/apcupsd.conf
roles/ispyagentdvr/defaults/main.yml
roles/ispyagentdvr/docs/ispyagentdvr.md
roles/ispyagentdvr/molecule/default/molecule.yml
roles/ispyagentdvr/molecule/default/side_effect.yml
roles/ispyagentdvr/molecule/default/verify.yml
roles/ispyagentdvr/molecule/default/verify_stopped.yml
roles/ispyagentdvr/requirements.yml
roles/ispyagentdvr/tasks/main.yml
roles/portainer/tasks/main.yml
website/docs/applications/system-tools/apcupsd.md

🔀 Pull upstream changes

---

README.md
nas.yml
roles/dozzle/defaults/main.yml
roles/dozzle/molecule/default/molecule.yml
roles/dozzle/molecule/default/side_effect.yml
roles/dozzle/molecule/default/verify.yml
roles/dozzle/molecule/default/verify_stopped.yml
roles/dozzle/requirements.yml
roles/dozzle/tasks/main.yml
roles/dozzle/templates/users.yml.j2
website/docs/applications/observability/dozzle.md

:sparkles: Add Dozzle

---

README.md
nas.yml
roles/scribblers/defaults/main.yml
roles/scribblers/molecule/default/molecule.yml
roles/scribblers/molecule/default/side_effect.yml
roles/scribblers/molecule/default/verify.yml
roles/scribblers/molecule/default/verify_stopped.yml
roles/scribblers/requirements.yml
roles/scribblers/tasks/main.yml
website/docs/applications/gaming/scribblers.md

:sparkles: Add scribble.rs

---

.envrc
.gitignore
devenv.nix
devenv.yaml

Adds devenv development environment for nix users.
Fixes #

Add devenv

---

roles/affine/defaults/main.yml
roles/affine/molecule/default/molecule.yml
roles/affine/tasks/main.yml

<!--  Thanks for sending a pull request!  Here are some tips for you:
Fixes #

⬆️ Update affine

---

README.md
nas.yml
roles/sparkyfitness/defaults/main.yml
roles/sparkyfitness/docs/sparkyfitness.md
roles/sparkyfitness/molecule/default/molecule.yml
roles/sparkyfitness/molecule/default/side_effect.yml
roles/sparkyfitness/molecule/default/verify.yml
roles/sparkyfitness/molecule/default/verify_stopped.yml
roles/sparkyfitness/requirements.yml
roles/sparkyfitness/tasks/main.yml
website/docs/applications/other/sparkyfitness.md

✨ Add Sparky Fitness

---

.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
nas.yml
pyproject.toml
roles/arcane/defaults/main.yml
roles/arcane/docs/arcane.md
roles/arcane/molecule/default/molecule.yml
roles/arcane/molecule/default/side_effect.yml
roles/arcane/molecule/default/verify.yml
roles/arcane/molecule/default/verify_stopped.yml
roles/arcane/requirements.yml
roles/arcane/tasks/main.yml
website/docs/applications/development-tools/arcane.md

Add Arcane
